spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/likelionchokyulim
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.spl: debug
    org.hibernate.type: trace

